# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b7ed753d45ae51b992606bc15e12e85c8b65d7844ad03c489be9124d9b601728205813fe114e27768f5e6eb2de95ca5ced0b9fc7c0a04d7ef35dd0aa5de786

test:
  secret_key_base: 6b8670d34d9d5ab3b03a5f09511c0a2c2049754f949e39b6f4d7a7f07daf8f57ab587902ebe2a9dc48c54ea518e69b9a5e7c5a41552aa509744cfda0255c2d46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
